spring:
  kafka:
    producer:
      client-id: json-pos-simulator
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

application:
  configs:
    topic:
      name: pos-topic-json
